services:
  #.sandra is the namespace
  consul.sandra:
    container_name: consul
    image: hashicorp/consul:1.20
    ports:
      - "8500:8500"
    networks:
      - web

  hello-service:
    build: ./hello-service
    container_name: hello-service
    #since micro 2 is calling micro 1
    # ports:
    #   - "8081:80"
#    depends_on:
#      - consul
    networks:
      - web

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8082:80"
#    depends_on:
#      - consul
    networks:
      - web

networks:
  web:
    driver: bridge
