services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
# docker compose up -d