services:
#########################################
  # Service Discovery
#########################################
  consul:
    container_name: consul-service
    image: hashicorp/consul:1.20
    ports:
      - "8500:8500" # Consul UI
    networks:
      - web
    restart: always

#########################################
  # Gateway Service Containers
#########################################
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8082:80"
    depends_on:
      - consul
    networks:
      - web


#######################################
# User-Service containers
#######################################

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:80"
    depends_on:
      - consul
    networks:
      - web

#######################################
# User-Postgres containers
#######################################
  user-postgres:
   image: postgres:16.3-alpine
   container_name: user-postgres
   restart: always
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: postgres
   ports:
     - "5433:5432"
   networks:
     - web

#######################################
# DB-UI containers
####################################### 
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
     - web
#Containers connected to the same bridge network can communicate with each other
networks:
  web:
    driver: bridge