services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"

  jaeger:
    image: jaegertracing/jaeger:2.1.0
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"
      - "4318:4318"   # OTLP HTTP
      - "5778:5778"
      - "9411:9411" 

# docker compose up -d