
services:
  # Service Discovery
  consul.diwakar:
    container_name: consul-service
    image: hashicorp/consul:1.20
    ports:
      - "8500:8500" # Consul UI
    networks:
      - web
    restart: always

  # Gateway Service Containers
#########################################
  gateway-service.diwakar:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "80:80"
    depends_on:
      - consul.diwakar
    networks:
      - web


#######################################

# User-Service containers
#######################################

  user-service.diwakar:
    build: ./user-service
    container_name: user-service
    depends_on:
      - consul.diwakar
    networks:
      - web

  user-postgres.diwakar:
    image: postgres:16.3-alpine
    container_name: user-postgres.diwakar
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes: #setting the data directory in the project
      - ./project-db/user-postgres/postgres/:/var/lib/postgresql/data/
    networks:
      - web

  kafka-user-service.diwakar:
    image: apache/kafka:3.9.0
    container_name: kafka-user-service
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-user-service.diwakar:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - web

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka-user-service.diwakar
    environment:
      KAFKA_CLUSTERS_0_NAME: user-service-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-user-service.diwakar:9092
      KAFKA_CLUSTERS_1_NAME: order-service-cluster
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: kafka-order-service.diwakar:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - web


  # Product Service Containers
  #######################################

  product-service.diwakar:
    build: ./product-service
    container_name: product-service
    #    ports:
    #      - "8081:80"
    depends_on:
      - consul.diwakar
      - product-postgres.diwakar
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - web
    volumes: #setting the data directory in the project
      - ./project-db/order-postgres/postgres/:/var/lib/postgresql/data/

  product-postgres.diwakar:
    image: postgres:16.3-alpine
    container_name: product-postgres.diwakar
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    networks:
      - web
#######################################

  # Order Service Containers
  #######################################

  order-service.diwakar:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:80"
    depends_on:
      - consul.diwakar
      - order-postgres.diwakar
    networks:
      - web

  order-postgres.diwakar:
    image: postgres:16.3-alpine
    container_name: order-postgres.diwakar
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    networks:
      - web

  kafka-order-service.diwakar:
    image: apache/kafka:3.9.0
    container_name: kafka-order-service
    ports:
      - "9093:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-order-service:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    networks:
      - web


  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    networks:
      - web

#docker compose up --build -d --scale user-service=3 // note we cant provide a name to container in this case

#Containers connected to the same bridge network can communicate with each other
networks:
  web:
    driver: bridge